---
# tasks file for ossec-server
- name: Install ossec server required packages for compilation
  yum: state=latest name={{ item }}
  with_items:
    - epel-release
    - python-lxml
    - wget
    - firewalld

- name: Download atomic repository
  get_url: 
    url: http://www.atomicorp.com/installers/atomic 
    mode: u+rwx
    dest: /tmp/atomic-repo-installer.sh
  when: ossec_install_atomic_repo

- name: Install atomic repository
  command: /tmp/atomic-repo-installer.sh
  environment:
    NON_INT: 1
  register: command_result
  failed_when: "'Error' in command_result.stderr"
  when: ossec_install_atomic_repo
# da verificare l'effettivo messaggio di errore quando fallisce
# il comando manuale: wget -q -O - http://www.atomicorp.com/installers/atomic | sh
# impostando export NON_INT=1 non vengono fatte le domande

#- name: Install or upgrade ossec-hids-server
#  yum: name={{ item }}
#       state=latest
#  with_items:
#    - ossec-hids
#    - ossec-hids-server
#  when: ossec_upgrade

#- name: Install ossec-hids-server
#  yum: name={{ item }}
#       state=present
#  with_items:
#    - ossec-hids
#    - ossec-hids-server
#  when: not ossec_upgrade

- name: delete atomic repo
  file:
    path: /etc/yum.repos.d/atomic.repo
    state: absent
  when: not ossec_install_atomic_repo

- name: copy file hids-ossec
  copy:
    src: files/ossec-hids-2.9.1-1764.el7.art.x86_64.rpm
    dest: /tmp/ossec-hids-2.9.1-1764.el7.art.x86_64.rpm

- name: copy file hids-ossec-server
  copy:
    src: files/ossec-hids-server-2.9.1-1764.el7.art.x86_64.rpm
    dest: /tmp/ossec-hids-server-2.9.1-1764.el7.art.x86_64.rpm

- name: copy file hids-ossec-mysql
  copy:
    src: files/ossec-hids-mysql-2.9.1-1764.el7.art.x86_64.rpm
    dest: /tmp/ossec-hids-mysql-2.9.1-1764.el7.art.x86_64.rpm

- name: install hids-ossec
  yum:
    name: /tmp/ossec-hids-2.9.1-1764.el7.art.x86_64.rpm
    state: present

- name: install hids-ossec-server
  yum:
    name: /tmp/ossec-hids-server-2.9.1-1764.el7.art.x86_64.rpm
    state: present

- name: install hids-ossec-mysql
  yum:
    name: /tmp/ossec-hids-mysql-2.9.1-1764.el7.art.x86_64.rpm
    state: present    

- name: delete comment line with xml syntax error in ossec.conf
  lineinfile:
    dest: /var/ossec/etc/ossec.conf
    state: absent
    regexp: '^ *<!-- Frequency'
# Attenzione dalla versione 2.3 e' stato cambiato il parametro dest a path

- name: Change ossec mail notification enable or disable
  xml:
    path: /var/ossec/etc/ossec.conf
    xpath: /ossec_config/global/email_notification
    value: '{{ ossec_email_notification }}'

- name: Change ossec mail to
  xml:
    path: /var/ossec/etc/ossec.conf
    xpath: /ossec_config/global/email_to
    value: '{{ ossec_email_to }}'

- name: Change ossec smtp server
  xml:
    path: /var/ossec/etc/ossec.conf
    xpath: /ossec_config/global/smtp_server
    value: '{{ ossec_smtp_server }}'

- name: Change ossec mail alert level
  xml:
    path: /var/ossec/etc/ossec.conf
    xpath: /ossec_config/alerts/email_alert_level
    value: '{{ ossec_email_alert_level }}'

- name: Change ossec mail from
  xml:
    path: /var/ossec/etc/ossec.conf
    xpath: /ossec_config/global/email_from
    value: '{{ ossec_email_from }}'

- name: Change ossec active response host-deny
  xml:
    path: /var/ossec/etc/ossec.conf
    xpath: /ossec_config/active-response[command="host-deny"]/disabled
    value: '{{ ossec_active_response_disabled }}'

- name: Change ossec active response firewall-drop
  xml:
    path: /var/ossec/etc/ossec.conf
    xpath: /ossec_config/active-response[command="firewall-drop"]/disabled
    value: '{{ ossec_active_response_disabled }}'

- name: Change ossec json output
  xml:
    path: /var/ossec/etc/ossec.conf
    xpath: /ossec_config/global/jsonout_output
    value: '{{ ossec_jsonout_output }}'

- name: remove xml header
  lineinfile:
    dest: /var/ossec/etc/ossec.conf
    state: absent
    regexp: '^<\?xml'
#  notify: restart ossec


- name: disable ossec rids
  lineinfile:
    path: /var/ossec/etc/internal_options.conf
    regexp: '^remoted.verify_msg_id'
    line: 'remoted.verify_msg_id=0'
  when: ossec_disable_rids == 'true'

- name: enable ossec rids
  lineinfile:
    path: /var/ossec/etc/internal_options.conf
    regexp: '^remoted.verify_msg_id'
    line: 'remoted.verify_msg_id=1'
  when: ossec_disable_rids == 'false'

- name: firewall enable port 1514 for ossec
  firewalld:
    port: 1514/udp
    permanent: true
    state: enabled    

- name: firewall enable port 514 for syslog tcp
  firewalld:
    port: 514/tcp
    permanent: true
    state: enabled   

- name: firewall enable port 514 for syslog udp
  firewalld:
    port: 514/udp
    permanent: true
    state: enabled        

- name: firewall enable port 1515 for ossec-authd
  firewalld:
    port: 1515/tcp
    permanent: true
    state: enabled   
    